"""
Django settings for drf_movie project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fvo!zu(&ke19&65z#rcj#$1lbam7q@kuml#vyypujd%f!5whiv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'movie',
    'rest_framework',
    'django_filters',
    'djoser',
    'account',
    'trade',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'drf_movie',
        'USER': 'root',
        'PASSWORD': 'dhl199900'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
APPEND_SLASH = True

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',)
}

from datetime import timedelta
SIMPLE_JWT = {
   'AUTH_HEADER_TYPES': ('JWT',),
   'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10),
   'REFRESH_TOKEN_LIFETIME': timedelta(minutes=200),
}

# Email configeration 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'freyadu99@gmail.com'
EMAIL_HOST_PASSWORD = 'nucpmzunazigixhp'
DEFAULT_FROM_EMAIL = 'freyadu99@gmail.com'
EMAIL_USE_TLS = True

# Djoser config
DJOSER = {
   'USER_ID_FIELD': 'username',
   'LOGIN_FIELD': 'email',
   'SEND_ACTIVATION_EMAIL': True,
   'ACTIVATION_URL': 'activate/{uid}/{token}',
   'SEND_CONFIRMATION_EMAIL': True,
   'PASSWORD_RESET_CONFIRM_URL': 'password_reset/{uid}/{token}',
   'PASSWORD_RESET_CONFIRM_RETYPE': True,
   'PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND': True,
   'SET_PASSWORD_RETYPE': True,
   
   'SERIALIZERS': {
       "user_create": "account.serializers.CustomUserCreateSerializer",
       "current_user": "account.serializers.CustomUserSerializer",
   },
}


# Alipay settings

ALIPAY_SERVER_URL = 'https://openapi-sandbox.dl.alipaydev.com/gateway.do'
ALIPAY_APP_ID = '2021000143601997'
ALIPAY_APP_PRIVATE_KEY = 'MIIEogIBAAKCAQEAwwGIYGrTC83b9e5mznz4WVyyUz9x1Z00uXMLXWuseUgjbYmSazE+v0KyE/99IhsIo7Th49VyLvsAsBqqdD0rS2Ga8kF7iElaXfUVtZIdMmrEpezwcAsrBxUEuYvO3rBKW1nTMVpoOHUm/xZ/fd1H3FyTHvOdzwZX1MaXdhM9B3kEhGUw1c6N5O/5bzRMWfFOUWs5Yq4CpcQxLKEcBJsxLyuEvkSeLZ2+0NIRRJ+ws658leWwtWwPvwrHGubIenZKD1l8Bk2B1umJYGr0VyQB1YHFNE3pWo7faivt3VpcM1QyEtY3bnP0V7ZFM2VeJ3OWENtZQXw5qahwuv76JVGVAwIDAQABAoIBACfIVkQlRuzvkGI5wqt5f0jryk2Fcfm8WpdCyxzB7KvJdcDRAhfwMfbe6ml+A89DaJ3NNxA96U+AUYGbzw5rtDtqrCukBEmnfVIRv94M8vvoIDohfmO9Q4fsV8xqo0d2+5RrXNSCtyRdchk0Q8ovrIteL31vAdDMYHq+EQQ7pIWzZVlYj9FxOoXnfaIZsCAdlC6mykjMuBF0s2kiVPe1vRUZC1OuYXt4+uAjyZTux+NuB/CQs5oSmruXgkdd2FhKTxzUlrh5FU82N4hZjkwLMVu1O11f6cd4zi3eezBAK59AdSjiLM9tt6spNpYDqa8wL3A/arerZW0eNWbSqufsWOECgYEA60N91pz0fSXV3qrx1b83iWFwiyCYcB8FYLVJ9A7nex5SgqU/AAq5z5ffrVErSrzc5zJTWnZ1iZRp7yd1zRsu3vn3Z9SqDs9mp71QwPzvbmWTBspSlfznMTFDxp3FwkD9HxEQcyI04mZRzSSWSf/MRqY2GsuFnbczWdOEccBzMPkCgYEA1DGqBTUxm5TTCdkkqmu+ZbGxhRllZnIgyzkUBgemECg+Sh2837MZbOwnPhBSakmTNqy9kYLk0QdkflznDMsuTvQSjKYO3r8ks1P29QQqvuJsI2x8Fq43QQf97DjkJFEAydagjNrOsUUz4Ltl9zAUtMY64ZNLfM29YUC0NbRYMNsCgYBLOj2WzoFvMxX8KXVC/+3mQ/4Uvst/rqutjMqk+88RE1UW6XgHr2ZS9yFS7k2FjHamhvUYTCCxaX+mNVv5xeNq8UsnLF1kdvVAVczoqPh2uIwW88MMqt3SYQpnDDQcNWO6913nMtzuOAGYM0bLSrwrKyLJ1qJXGCmXY4dKSFuNIQKBgBCqMdsk2VeJsaVVW27S9WoRMYrteqw4DGFJg0wR77XXI0U43quG6llGlrJmH8LfMmOZ3219JTFRblAKRc8YafOjcY2AQSy3QE+hKYUGpcDGEY4aqAgz+Hzv/r49nZVIk1JGu+c0DAWaFL/yl8h5CzdDVj5/De+oTNZFeaG6Hy7/AoGAfiJS8kuUQnATjwN/vCaIMGyfAt0JC9JzGrSJP/vwRmujzo0PXdjFfR4oc+RNbs/K8uubpBQ7KOKcp7n4t2IFgfOn5yTNvBGxFQ0LFs24hczQ19AhPSgQeeDqt1hLCOA+sVE9Jds+ALR35wzUb8TRac6KiBRwCzjhoBVPgySPirM='
ALIPAY_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuKVhRtL5IOKYKcE6NNiav6FOBoD3zrs4VM6ujpVvsFkEzqbFLEGE6dIwYLFU1RrJKEAvQ3Xc+GElUCVAEXMNMYkyGn1iaBJBsm0LTCiu2mQ6pqBOVPw/9o9Wd1dES2fqDLyeQPk32wzHDZGeV+MzIvRgryZN3pUDxkDMt9LZYq6y8HQSCoboKOmWmQ41EXygnZIB9E+eeaq/V+DJx1KlE53QqGg14jyD6t6v5I2aUfKOx8ghKiIPiqzc/cMn+F676ZS877Ix0oMq/ElGps1DQqCDQWscyJVCu4wE6ygfmyTY2rU8/1RtaGoT/Eh9cZtepOUXGDEOTH1YcinB/WRLLQIDAQAB'
# return url 
ALIPAY_RETURN_URL = 'http://5d70522d.r30.cpolar.top/orders/'
# notifyURL
ALIPAY_NOTIFY_URL = 'http://5d70522d.r30.cpolar.top/api/callback/'
# seller_id
ALIPAY_SELLER_ID = '2088721053871105'


# Note
"""
superuser: admin2 password: dhl123456
user1: freyadu password: dhl123456
cpolar: hd2367@nyu.edu password: DHLdhl1974&*

宝塔面板
username：duhanlu password: b6f0e837
宝塔账号: 17753563082 password: DHLdhl1974&*
"""