# Generated by Django 4.2.4 on 2024-12-13 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0002_rename_release_data_movie_release_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True, verbose_name='unique id')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=11, null=True, verbose_name='user phone number')),
                ('email', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='user email')),
                ('avatar', models.CharField(blank=True, max_length=60, null=True, verbose_name='user avatar')),
                ('is_upgrade', models.IntegerField(default=0, verbose_name='if upgrade')),
                ('upgrade_time', models.DateTimeField(blank=True, null=True, verbose_name='upgrade date')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='expire date')),
                ('upgrade_count', models.IntegerField(default=0, verbose_name='upgrade count')),
                ('movies', models.ManyToManyField(to='movie.movie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user info',
                'verbose_name_plural': 'user info',
                'db_table': 'profile',
            },
        ),
    ]
