# Generated by Django 4.2.4 on 2024-12-28 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100, unique=True, verbose_name='membership name')),
                ('card_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price')),
                ('duration', models.IntegerField(verbose_name='duration')),
                ('info', models.CharField(blank=True, max_length=200, null=True, verbose_name='membership info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update time')),
            ],
            options={
                'verbose_name': 'card info',
                'verbose_name_plural': 'card info',
                'db_table': 'card',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='order number')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='trade number')),
                ('pay_status', models.CharField(choices=[('WAIT_BUYER_PAY', 'trade created'), ('TRADE_SUCCESS', 'trade success'), ('TRADE_CLOSED', 'trade closed'), ('TRADE_FINISHED', 'trade finished'), ('PAYING', 'wait for payment')], default='PAYING', max_length=30, verbose_name='order status')),
                ('pay_type', models.CharField(choices=[('alipay', 'alipay'), ('wechat', 'wechat')], default='alipay', max_length=10, verbose_name='payment type')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='order amount')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='payment time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trade.card', verbose_name='membership card')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'order info',
                'verbose_name_plural': 'order info',
                'db_table': 'order',
            },
        ),
    ]
