# Generated by Django 4.2.4 on 2024-12-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_CLOSED', 'trade closed'), ('TRADE_SUCCESS', 'trade success'), ('TRADE_FINISHED', 'trade finished'), ('PAYING', 'wait for payment'), ('WAIT_BUYER_PAY', 'trade created')], default='PAYING', max_length=30, verbose_name='order status'),
        ),
    ]
