# Generated by Django 4.2.4 on 2024-11-22 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'category management',
                'verbose_name_plural': 'category management',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100, verbose_name='movie name')),
                ('release_year', models.IntegerField(verbose_name='release year')),
                ('director', models.CharField(max_length=100, verbose_name='director')),
                ('scriptwriter', models.CharField(max_length=200, verbose_name='script writer')),
                ('actors', models.CharField(max_length=200, verbose_name='actor')),
                ('region', models.SmallIntegerField(choices=[(1, 'China mainland'), (2, 'China HongKong'), (3, 'United States'), (4, 'South Korean'), (5, 'Japan'), (6, 'Other')], verbose_name='region')),
                ('types', models.CharField(max_length=200, verbose_name='types')),
                ('language', models.CharField(max_length=200, verbose_name='language')),
                ('release_data', models.DateField(verbose_name='release data')),
                ('alternate_name', models.CharField(blank=True, max_length=100, verbose_name='alternate name')),
                ('duration', models.CharField(max_length=50, verbose_name='duration')),
                ('image_url', models.CharField(max_length=200, verbose_name='image url')),
                ('rate', models.FloatField(blank=True, verbose_name='rate')),
                ('review', models.TextField(max_length=500, verbose_name='review')),
                ('is_hot', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='if hot')),
                ('is_top', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='if on the top')),
                ('quality', models.SmallIntegerField(choices=[(1, '720P'), (2, '1080P'), (3, '4K')], verbose_name='quality')),
                ('subtitle', models.CharField(blank=True, max_length=100, verbose_name='subtitle')),
                ('update_info', models.CharField(blank=True, max_length=100, verbose_name='update info')),
                ('update_progress', models.CharField(blank=True, max_length=100, verbose_name='update progress')),
                ('download_info', models.TextField(blank=True, max_length=500, verbose_name='download info')),
                ('is_show', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=True, verbose_name='if showing')),
                ('is_free', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='if free')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.category', verbose_name='category name')),
            ],
            options={
                'verbose_name': 'movie management',
                'verbose_name_plural': 'movie management',
                'db_table': 'movie',
            },
        ),
    ]
